development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      # database: mongoid_test_development
      # hosts:
      #   - localhost:27017

test:
  host: localhost
  database: mongoid_test_test

# set these environment variables on your prod server
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        max_pool_size: 100
        min_pool_size: 1